services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - node
    networks:
      - fullcycle-network

  node:
    container_name: node
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    build:
      context: ./node
    depends_on:
      - db
    tty: true
    networks:
      - fullcycle-network
    volumes:
      - ./node:/app

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - fullcycle-network
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  fullcycle-network:
    driver: bridge